//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemNhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int id { get; set; }
        public string nameproduct { get; set; }
        public int price { get; set; }
        public int soluong { get; set; }
        public sanpham SelectedItem { get; internal set; }
        public List<sanpham> DataSource { get; internal set; }
        public string ValueMember { get; internal set; }
        public string DisplayMember { get; internal set; }
    }
}
